events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 8080;
        listen [::]:8080;

        server_name escreveai.api;

        root /var/www/api/public;

        add_header X-Content-Type-Options "nosniff";

        index      index.php;
        charset    utf-8;

        error_page 404 /index.php;

        location / { try_files $uri $uri/ /index.php?$query_string; }

        location ~ ^/index\.php(/|$) {
                fastcgi_pass    php-fpm:9000;

                fastcgi_param   SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

                include fastcgi_params;

                fastcgi_buffer_size         32K;
                fastcgi_buffers             8 32K;
                fastcgi_busy_buffers_size   64K;

                fastcgi_hide_header         X-powered-By;
        }

        location ~ /\.(?!well-known).* { deny all; }
    }

    server {
        listen 80;
        listen [::]:80;

        server_name escreveai;

        root /var/www/public;

        index      /pages/home.html;
        error_page 404 /pages/notfound.html;

        charset    utf-8;

        location / {
            try_files $uri $uri/ /pages/$uri =404;
        }
    }
}
